import React, { useState, useEffect } from 'react';
import { analytics } from '../utils/analytics';
import { QrCode, BarChart3, Smartphone, Flame, RefreshCcw, X, ClipboardCheck, ExternalLink, Printer } from 'lucide-react';

export default function Dashboard({ onClose }) {
  const [stats, setStats] = useState(analytics.getStats());

  useEffect(() => {
    setStats(analytics.getStats());
  }, []);

  const handleReset = () => {
    if (window.confirm("Are you sure you want to reset all analytics data? This cannot be undone.")) {
      analytics.clearStats();
      setStats(analytics.getStats());
    }
  };

  return (
    <div className="w-full max-w-xl mx-auto p-6 rounded-3xl border border-luxury-border bg-luxury-card backdrop-blur-3xl shadow-gold-glow-lg text-luxury-textLight animate-slide-up space-y-6">
      
      {/* Dashboard Header */}
      <div className="flex items-center justify-between pb-4 border-b border-luxury-border">
        <div className="flex items-center gap-2">
          <BarChart3 className="w-5 h-5 text-gold-600" />
          <h2 className="font-serif text-xl font-bold tracking-wide text-luxury-textLight">
            Baghpat Analytics Dashboard
          </h2>
        </div>
        <button
          onClick={onClose}
          className="p-1 rounded-lg text-luxury-textMuted hover:text-luxury-textLight hover:bg-black/5 transition-all cursor-pointer"
          aria-label="Close Dashboard"
        >
          <X className="w-5 h-5" />
        </button>
      </div>

      {/* Grid of Key Stats */}
      <div className="grid grid-cols-2 gap-3.5">
        {/* Scans */}
        <div className="p-4 rounded-2xl border border-luxury-border bg-[#F5F5F7]/80 shadow-inner flex flex-col justify-between">
          <div className="flex items-center justify-between text-luxury-textMuted font-bold">
            <span className="text-[10px] uppercase tracking-wider">QR Scans</span>
            <Smartphone className="w-4 h-4 text-sky-600" />
          </div>
          <p className="text-3xl font-sans font-extrabold text-luxury-textLight mt-2">{stats.qrScans}</p>
          <span className="text-[9px] text-luxury-textMuted mt-1">Total visits recorded</span>
        </div>
 
        {/* Generated */}
        <div className="p-4 rounded-2xl border border-luxury-border bg-[#F5F5F7]/80 shadow-inner flex flex-col justify-between">
          <div className="flex items-center justify-between text-luxury-textMuted font-bold">
            <span className="text-[10px] uppercase tracking-wider">Generated Drafts</span>
            <QrCode className="w-4 h-4 text-gold-600" />
          </div>
          <p className="text-3xl font-sans font-extrabold text-luxury-textLight mt-2">{stats.reviewsGenerated}</p>
          <span className="text-[9px] text-luxury-textMuted mt-1">Drafts generated by users</span>
        </div>
 
        {/* Copied */}
        <div className="p-4 rounded-2xl border border-luxury-border bg-[#F5F5F7]/80 shadow-inner flex flex-col justify-between">
          <div className="flex items-center justify-between text-luxury-textMuted font-bold">
            <span className="text-[10px] uppercase tracking-wider">Copied Review</span>
            <ClipboardCheck className="w-4 h-4 text-emerald-600" />
          </div>
          <p className="text-3xl font-sans font-extrabold text-luxury-textLight mt-2">{stats.copyClicks}</p>
          <span className="text-[9px] text-luxury-textMuted mt-1">Reviews copied to clipboard</span>
        </div>
 
        {/* Redirect Clicks */}
        <div className="p-4 rounded-2xl border border-luxury-border bg-[#F5F5F7]/80 shadow-inner flex flex-col justify-between">
          <div className="flex items-center justify-between text-luxury-textMuted font-bold">
            <span className="text-[10px] uppercase tracking-wider">Google Clicks</span>
            <ExternalLink className="w-4 h-4 text-purple-650" />
          </div>
          <p className="text-3xl font-sans font-extrabold text-luxury-textLight mt-2">{stats.googleClicks}</p>
          <span className="text-[9px] text-luxury-textMuted mt-1">Clicks to write a review</span>
        </div>
      </div>

      {/* Conversion Rate Meter */}
      <div className="p-4 rounded-2xl border border-luxury-border bg-[#F5F5F7]/80 space-y-2">
        <div className="flex justify-between items-center text-xs font-sans font-bold">
          <span className="text-luxury-textMuted uppercase tracking-wider text-[9px]">Google Review Click Rate</span>
          <span className="text-gold-600">
            {stats.qrScans > 0 ? Math.round((stats.googleClicks / stats.qrScans) * 100) : 0}%
          </span>
        </div>
        <div className="w-full bg-[#E5E5EA] h-2 rounded-full overflow-hidden">
          <div 
            className="bg-gold-500 h-full rounded-full transition-all duration-500" 
            style={{ width: `${stats.qrScans > 0 ? Math.min(100, Math.round((stats.googleClicks / stats.qrScans) * 100)) : 0}%` }}
          />
        </div>
      </div>

      {/* Popular Checklist Keywords (Most Mentioned) */}
      <div className="p-4 rounded-2xl border border-luxury-border bg-[#F5F5F7]/60 space-y-3">
        <h3 className="text-xs uppercase font-bold tracking-wider text-gold-600 flex items-center gap-1.5">
          <Flame className="w-4 h-4 text-amber-500 fill-amber-500/10" />
          Most Mentioned Keywords
        </h3>
        <div className="space-y-2 font-semibold">
          {stats.dishesRanking.slice(0, 5).map((dish, index) => (
            <div key={dish.name} className="flex items-center justify-between text-xs font-sans">
              <div className="flex items-center gap-2">
                <span className="w-4 text-luxury-textMuted font-bold text-right">{index + 1}.</span>
                <span className="text-luxury-textLight">{dish.name}</span>
              </div>
              <div className="flex items-center gap-2">
                <div className="w-24 bg-[#E5E5EA] h-1.5 rounded-full overflow-hidden hidden sm:block">
                  <div 
                    className="bg-gold-400 h-full rounded-full" 
                    style={{ width: `${stats.reviewsGenerated > 0 ? (dish.count / stats.reviewsGenerated) * 100 : 0}%` }}
                  />
                </div>
                <span className="font-bold text-gold-600">{dish.count} times</span>
              </div>
            </div>
          ))}
          {stats.dishesRanking.filter(d => d.count > 0).length === 0 && (
            <p className="text-xs text-luxury-textMuted italic text-center py-2">No selections recorded yet</p>
          )}
        </div>
      </div>

      {/* QR Code Table Placement Section */}
      <div className="p-4 rounded-2xl border border-gold-400/20 bg-gold-50/50 space-y-3">
        <h3 className="text-xs uppercase font-bold tracking-wider text-gold-600 flex items-center gap-1.5">
          <Printer className="w-4 h-4 text-gold-600" />
          QR Placement Best Practices
        </h3>
        <div className="text-xs text-luxury-textLight font-sans leading-relaxed space-y-2 font-semibold">
          <p>
            Placing QR codes contextually across the cafe increases the review collection rate by up to <span className="text-gold-600 font-extrabold">300%</span>:
          </p>
          <ul className="list-disc list-inside space-y-1 text-luxury-textMuted pl-1">
            <li><span className="text-luxury-textLight font-bold">Dining Tables</span>: Under a mini-acrylic stand with "Loved your food? Scan to share".</li>
            <li><span className="text-luxury-textLight font-bold">Billing Counter</span>: A gold badge near the card scanner.</li>
            <li><span className="text-luxury-textLight font-bold">Menu Cards</span>: Small QR footer on the back page.</li>
            <li><span className="text-luxury-textLight font-bold">Exit Doors / Handwash</span>: "Feedback helps us grow" sign board.</li>
          </ul>
        </div>
      </div>

      {/* Action Footer */}
      <div className="flex justify-between items-center pt-2">
        <button
          onClick={handleReset}
          className="flex items-center gap-1 text-[10px] font-sans font-bold text-red-650 hover:text-red-700 transition-colors uppercase tracking-wider py-1 cursor-pointer"
        >
          <RefreshCcw className="w-3 h-3" />
          <span>Reset Stats</span>
        </button>
        <span className="text-[10px] text-luxury-textMuted font-sans font-bold">Chapter One Cafe Baghpat &copy; 2026</span>
      </div>

    </div>
  );
}
